### ISSUE TITLE
Using Unsupported mongoose version, highest supported is 5.10.18 (Current version: 5.11.13)

### ISSUE THREAD

**Issue by SurgicalCrow** [ItsDizzy/commando-provider-mongo#15]
Hey, i am getting this logged in console, is that coming from your package, can you please check out this :( 
Also
```1|rg  | (node:244799) DeprecationWarning: current Server Discovery and Monitoring engine is deprecated, and will be removed in a future version. To use the new Server Discover and Monitoring engine, pass option { useUnifiedTopology: true } to the MongoClient constructor.```

**Comment by paulhobbel** [comment]
Just pass that option to the MongoClient constructor and you should be good.

**Comment by SurgicalCrow** [comment]
@paulhobbel are you using an unsupported version of mongoose? i am getting this error as well,, while using the mongodb provider for commando 

```2|rg  | Using Unsupported mongoose version, highest supported is 5.10.18 (Current version: 5.11.16)```

**Comment by paulhobbel** [comment]
There is no mongoose dependency in commando-provider-mongo.
commando-provider-mongo only has peer dependencies, one of which is the mongodb client, not mongoose

**Comment by paulhobbel** [comment]
Closing this as this is not something I can fix
