### ISSUE TITLE
Dependency Errors

### ISSUE THREAD

**Issue by aedithan** [ItsDizzy/commando-provider-mongo#16]
I'm receiving the following dependency error when installing this package.

![image](https://user-images.githubusercontent.com/22295315/107686847-52b7a680-6c6b-11eb-9952-199a32054ec2.png)

**Comment by paulhobbel** [comment]
Looking into it now

**Comment by paulhobbel** [comment]
Seems like Commando received an update after 3 years, will bring out a patch today

**Comment by paulhobbel** [comment]
A fix has been made in #17. Will push a new release to NPM.
Released as version `2.1.0`

**Comment by aedithan** [comment]
New release 2.1.0 installs without error. Thank you for looking into this.
