### ISSUE TITLE
Prefix won't update if I make changes from my database.

### ISSUE THREAD

**Issue by ghost** [ItsDizzy/commando-provider-mongo#18]
I'm trying to change the prefix from my mongodb database directly for my dashboard but it seems like commando-provider-mongo stores the prefixes in a cache. Is there any way to update the cache so that it notices I've changed the command prefix change from the database?

**Comment by paulhobbel** [comment]
Hi sorry I missed your issue. This is indeed because values are cached. A reboot will fix it, could add an option to remove caching. Maybe there's a Commando feature to reload a provider?

**Comment by TheIdealMatrix** [comment]
Instead updating the prefix in the database update it in the Commando Client. It will then save automatically to the database throu the provider. -> https://discord.js.org/#/docs/commando/master/class/CommandoGuild?scrollTo=commandPrefix

Example: `client.guilds.cache.get('GUILD_ID').commandPrefix = 'NEW_PREFIX'`

If your webserver is not running on the same process with your Bot then you will probably have to comunicate with the bot throu an API which you have to create.
