### ISSUE TITLE
Dependancy issues, Update to djs v 13

### ISSUE THREAD

**Issue by nathen418** [ItsDizzy/commando-provider-mongo#19]
I am getting an error when I try to install with discord.js v13.1.0 and discord.js-commando v0.12.3.

If it needs to be fixed for djs13 please update, or advise what I should do. Screenshot of error below:
![image](https://user-images.githubusercontent.com/23101313/133935262-5700de69-e0a1-43bd-a437-e43ab6ec10f1.png)

Thanks,
Nate

**Comment by paulhobbel** [comment]
Working on it, sorry for the long wait

**Comment by paulhobbel** [comment]
Commando does not support DiscordJS 13: https://github.com/discordjs/Commando/issues/413
