### ISSUE TITLE
No longer operational for Discord.js v12

### ISSUE THREAD

**Issue by Lexouden** [ItsDizzy/commando-provider-mongo#4]
### Issue

Since in DJS v12 all `Client#guilds` have been added to a `GuildManager` so the package now throws a TypeError: `client.guilds.has is not a function`.

### Solution
To fix this you'll have to update the package.

**Comment by paulhobbel** [comment]
Will take a look, this package reserves an update anyways

**Comment by Lexouden** [comment]
It might also be caused by an outdated `discord.js-commando` dependency

**Comment by jonahsnider** [comment]
The way I handled this in a backwards compatible way was
```js
(​client​.​guilds​.​cache​ ​||​ ​client​.​guilds​)
```
More modern syntax would use the nullish coalescing operator instead of the logical OR.
