### ISSUE TITLE
How can I use my own mongoose.Schema

### ISSUE THREAD

**Issue by BenjiCS** [ItsDizzy/commando-provider-mongo#8]
I want to use my own database on Mongodb 
This is my Schema 
`const mongoose = require("mongoose");`
`const GuildConfigSchema = new mongoose.Schema({`
`  guildId: {`
`    type: String,`
`    required: true,`
`    unique: true,`
`  },`
`  prefix: {`
`    type: String,`
`    required: true,`
`    default: "!",`
`  },`
`  defaultRole: {`
`    type: String,`
`    required: false,`
`  },`
`  memberLogChannel: {`
`    type: String,`
`    required: false,`
`  },`
`});`
`module.exports = mongoose.model("GuildConfig", GuildConfigSchema);`

How can i use that in sted of the settings collection

**Comment by johnweland** [comment]
I am not 100% sure where the confusion is. However, I have a repo where I use this and mongoose. You are welcome to poke around the code. https://github.com/johnweland/discordbot. Notice: In index.js I call and use the provider then in have a mongo.js I use my mongoose code and then require that and my schema files wherever they are needed.

**Comment by BenjiCS** [comment]
> I am not 100% sure where the confusion is. However, I have a repo where I use this and mongoose. You are welcome to poke around the code. https://github.com/johnweland/discordbot. Notice: In index.js I call and use the provider then in have a mongo.js I use my mongoose code and then require that and my schema files wherever they are needed.

Ty i will look at it 🙂🙂

**Comment by BenjiCS** [comment]
@johnweland I cant get it to work as I want to but my question was 
I want Commando to get the prefix from my own schema becuse im working on a dashboard where you can set the prefix and im not that good at mongoDB yet

**Comment by MutantRabbit767** [comment]
I would just make another schema for prefix's alone, and then your dashboard could still have the prefix changer thing...

**Comment by paulhobbel** [comment]
I know this issue was closed a long time ago, if wanted I can make an extension to support mongoose
